### PR TITLE
Fixed Join function

### PR DESCRIPTION
**Pull request by chenglidev**

### CODE REVIEW

**Comment by chenglidev** [comment]
Join function was not working with a list parameter.
For example, `join(list('a', 'b', 'c'), ', ')` was throwing an exception.

**Comment by chenglidev** [comment]
Hi @davidnmbond and @danielabbatt,
Would you please merge these commits to upload a new version in nuget?
Thanks in advance.

**Review by danielabbatt — APPROVED** [review]
Thanks

**Comment by danielabbatt** [comment]
This will be available in https://www.nuget.org/packages/PanoramicData.NCalcExtensions/1.19.9

**Pull request merged**
